### ISSUE TITLE
Indexer discards pm file with $VERSION = 2017.100.1

### ISSUE THREAD

**Issue by andk** [andk/pause#246]
This was discovered with HURRICUP/Devel-Camelcadedb-v2017.100.1.tar.gz in the thread http://www.nntp.perl.org/group/perl.modules/2017/06/msg97518.html

Ron Savage suggests introducing at least an error message when this happens. Alternatively, we probably can support such version numbers?

**Comment by charsbar** [comment]
Because ```version::is_lax(2017.100.1)``` returns false, IMO we shouldn't support that version, at least for now. As the author uses "v" for the distribution version, it's probably better to ask the author to prepend "v" in the $VERSION as well, so that the module and the distribution use the same version scheme.

Something like this might help: https://github.com/charsbar/Parse-PMFile/blob/master/lib/Parse/PMFile.pm#L617-L619

**Comment by Grinnz** [comment]
Quoting the version so it is parsed as a string should at least solve this issue. The main problem is that it's being evaluated as a vstring literal.
