### ISSUE TITLE
Personal mention of admin instead of an admin role.

### ISSUE THREAD

**Issue by matthewpersico** [andk/pause#254]
From E. Choroba at http://blogs.perl.org/users/neilb/2017/10/the-pause-operating-model.html:

"...Also, I don't like how Andreas is mentioned in many places (nothing personal!). There should be a tie-breaker role, currently occupied by Andreas. It will make the document valid even for occasions of ANDK's absence."

**Comment by rjbs** [comment]
Agreed.

**Comment by rjbs** [comment]
I have gone through the document and decided that just replacing Andreas's name is not practical.  This is something we need to plan for as a matter of actual change, because the document (in this matter) really isn't describing an organization that has a role that Andreas performs, but a state of play that really does rely on Andreas personally.  We know we need better succession planning, but we'll need to do that, not just edit a doc.
