### ISSUE TITLE
Reappearing VMS::stdio instead of VMS::Stdio

### ISSUE THREAD

**Issue by andk** [andk/pause#265]
Email from Karen:

``` text
hi!

I see that the 02packages index file contains:

VMS::stdio 2.41 S/SH/SHAY/perl-5.24.4.tar.bz2

Could you please update the db entry so the module name is
"VMS::Stdio" (uppercased)? The module name was changed in PAUSE a long
time ago
(https://www.nntp.perl.org/group/perl.perl5.porters/2017/08/msg246083.html)
but for some reason new releases keep using the old entry. But we
really should fix this, so release tools do not fail with an error
that they cannot find the module in the pause index.

thank you!
-ether
```

Before doing a manual change to the involved tables, I'd like to have at least an hypothesis how it happened and how we want to prevent it from happening again.

**Comment by neilb** [comment]
Gotta go deal with kids and such, but I'll add a note explaining what happened, and why, later.

**Comment by neilb** [comment]
Here's the history and what I think is going on:

* Perl 5 first shipped with VMS::stdio
* Not long after -- I think it might have been 5.003, but I can't remember -- the module was renamed to VMS::Stdio, with a shim included for backwards compatibility, so you could use either VMS::Stdio or VMS::stdio
* Last year, as part of my project to resolve case-duplicate permissions, I hit this.
* I raised it on P5P and got the OK from Sawyer and others to send a patch which dropped the VMS::stdio shim. I sent the patch in August and dropped the PAUSE indexing permissions on VMS::stdio.
* I assume the first stable release with that change (no VMS::stdio shim) in will be the upcoming 5.28
* The next stable release of Perl after I dropped the perms on VMS::stdio obviously still had the version of VMS::Stdio with the shim (eg see [the version of VMS::Stdio in 5.26.2](https://metacpan.org/source/SHAY/perl-5.26.2/ext/VMS-Stdio/Stdio.pm)).
* Until [#250](https://github.com/andk/pause/issues/250) is fixed, releasing a module that includes multiple case variants of the same name will result in PAUSE indexing permissions on all variants of the package name, so indexing permissions were added back on VMS::stdio.
* Which resulted in VMS::stdio being indexed instead of VMS::Stdio
* Where there are permissions on multiple case-variants of the same package, PAUSE seems to get a bit confused, which I guess is why VMS::stdio is indexed against 5.24.4.

**Comment by karenetheridge** [comment]
aha! I looked in blead and didn't see recent changes to VMS::Stdio; I failed to look in the maint-5.26 branch *hangs head*
