### ISSUE TITLE
High number of indexing problems on PAUSE

### ISSUE THREAD

**Issue by eserte** [andk/pause#305]
It seems that yesterday (2019-02-11) around 15:00 a high number of freshly uploaded CPAN distributions was not indexed properly. I checked MetaCPAN's recent list and found this ones:
* https://metacpan.org/release/HOCHSTEN/Catmandu-BagIt-0.235 -> 0.234
* https://metacpan.org/release/RENEEB/Types-Mojo-0.03 -> 0.02
* https://metacpan.org/release/RENEEB/App-CPANCoverBadge-0.03 -> 0.02
* https://metacpan.org/release/TIEDEMANN/Text-PDF2XML-0.3.3 -> 0.3.2
* https://metacpan.org/release/EDF/Geo-Coder-OpenCage-0.17 -> 0.16
* https://metacpan.org/release/RRWO/PerlX-Let-v0.2.2 -> v0.2.1
* https://metacpan.org/release/JLMARTIN/Azure-AD-Auth-0.03 -> 0.02
* https://metacpan.org/release/KFLY/Function-Return-0.041 -> 0.031
* https://metacpan.org/release/JHTHORSEN/Devel-MojoProf-0.03 -> 0.02

Here I stopped. I checked the meta files of some of these and did not find any obvious problems.

**Comment by andk** [comment]
Thanks, all of those, that have not meanwhile repaired themselves, have now been indexed manually.

Plus a few more:

MARKOV/Mail-Message-3.008
RJH/Test-TempFile-0.91
SYBER/Test-Catch-1.0.2
COUDOT/Lemonldap-NG-Handler-2.0.2
CDRAUG/BioPerl-1.7.5

It's a resource contention that sometimes happens when people upload batches or huge distros.

Thanks for the heads up!
