### ISSUE TITLE
Remove old releases of a distribution from the index

### ISSUE THREAD

**Issue by neilb** [andk/pause#358]
If an author renames the modules in a distribution, and leaves old releases in their author directory on PAUSE,
then we end up with old releases appearing in the index.
This could result in someone installing the wrong version of a distribution,
and depending on the CPAN client, 
you could theoretically overwrite a distribution that's already installed, with an older version.

For example, there are 10 different releases of `DBIx-Class` listed in the index. I just installed the latest (0.082842) with

    cpan DBIx::Class

And then ran this:

    cpan DBIx::Class::UUIDMaker

Which tried to install DBIx-Class-0.06002, but fortunately for me that failed some tests, and so didn't overwrite.

The way we solve this right now is by getting people to delete old releases from author directories,
but as with DBIx-Class, these could be spread across multiple author directories:

    M/MR/MRAMBERG/DBIx-Class-0.03002.tar.gz
    D/DK/DKAMHOLZ/DBIx-Class-0.04001.tar.gz
    D/DK/DKAMHOLZ/DBIx-Class-0.05006.tar.gz
    M/MS/MSTROUT/DBIx-Class-0.05007.tar.gz
    E/EL/ELLIOTT/DBIx-Class-0.06002.tar.gz
    M/MS/MSTROUT/DBIx-Class-0.07000.tar.gz
    D/DA/DANIELTWC/DBIx-Class-0.07002.tar.gz
    A/AB/ABRAXXA/DBIx-Class-0.08195.tar.gz
    A/AR/ARODLAND/DBIx-Class-0.08196.tar.gz
    R/RI/RIBASUSHI/DBIx-Class-0.082842.tar.gz

It would be a lot safer if we removed old releases from the index when a new version is uploaded.

**Comment by andk** [comment]
>>>>> On Sun, 09 Aug 2020 04:33:55 -0700, Neil Bowers <notifications@github.com> said:

  > It would be a lot safer if we removed old releases from the index when
  > a new version is uploaded.

Since CPAN.pm version 2.27 you can configure the client with two new
options:

	allow_installing_outdated_dists and
	allow_installing_module_downgrades

I think using these options is the right approach for the enduser to
protect their own installations. Deleting history is too drastic for my
taste. Most of the time it seems easy to determine what one would
delete, but every so often the decision would be wrong. The decision
what need to be done should be left to the developers themselves. The
new options in CPAN.pm help to determine who to talk to or which
dependencies to tweak.

Please try the new options out!
-- 
andreas

**Comment by neilb** [comment]
> two new options: `allow_installing_outdated_dists` and `allow_installing_module_downgrades` 

Are these options enabled by default for new users of CPAN?

> Deleting history is too drastic for my taste.

I wasn't suggesting deleting the tarballs from author directories, just dropping packages from the index if they're not in the latest release of a distribution. I'm pretty sure you knew that, but just clarifying in case, and for the peanut gallery :-)

**Comment by andk** [comment]
>>>>> On Mon, 10 Aug 2020 04:08:22 -0700, Neil Bowers <notifications@github.com> said:

  >     two new options: allow_installing_outdated_dists and
  >     allow_installing_module_downgrades

  > Are these options enabled by default for new users of CPAN?

If you configure them interactively, the default suggestion is "ask/no".
If you do not configure them, the default is "ask/yes". Note, their
names are "allow", so yes means allow and no means disallow. The
defaults are configured with "ask/" for that reason, so the user has
time to get acquainted with them once they get in the way by asking a
queation.

  >     Deleting history is too drastic for my taste.

  > I wasn't suggesting deleting the tarballs from author directories,
  > just dropping packages from the index if they're not in the latest
  > release of a distribution. I'm pretty sure you knew that, but just
  > clarifying in case, and for the peanut gallery :-)

Thanks for the clarification, I was sloppy in my answer. I'm quite
convinced, we do not want to overrule the indexer's decision either way.
I think of the situation that we would probably unindex A in order to
support B and short after that the maintainer of B decides to delete B
in order to support A. We end up with neither A nor B and some extra
work required that probably nobody realizes.


-- 
andreas

**Comment by karenetheridge** [comment]
> The decision
what need to be done should be left to the developers themselves.

While i tentatively agree with this, we can help the developer by providing more information. How about, as a half-measure for now\*, we provide information when indexing the distribution when not every module previously indexed by the distribution is in the new upload?

\* and by "now", I really mean "whenever someone gets around to producing a patch", which might be years.. but that's the same situation as we were in earlier in this issue when other changes were being proposed :)

**Comment by neilb** [comment]
As ever, wise words from Andreas. And I like Karen's suggestion.

I'll close this and open a new issue for "tell uploader when there are old versions of the dist indexed".
